# Generated by Django 5.0.6 on 2024-07-24 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2024, 7, 24, 9, 21, 1, 143894),
                null=True,
                verbose_name="Время последнего посещения",
            ),
        ),
    ]
