# Generated by Django 5.0.6 on 2024-07-24 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 24, 9, 31, 6, 251936, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Время последнего посещения",
            ),
        ),
    ]
