# Generated by Django 5.0.6 on 2024-08-08 06:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Время последнего посещения",
            ),
        ),
    ]
