# Generated by Django 5.0.6 on 2024-07-11 07:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course", "0001_initial"),
        ("lesson", "0002_alter_lesson_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_payment", models.DateField(auto_now_add=True)),
                (
                    "sum",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Укажите сумму",
                        null=True,
                        verbose_name="Сумма",
                    ),
                ),
                (
                    "cash_payment",
                    models.BooleanField(
                        blank=True,
                        help_text="Выберите наличные",
                        null=True,
                        verbose_name="Наличные",
                    ),
                ),
                (
                    "payment_to_account",
                    models.BooleanField(
                        blank=True,
                        help_text="Выберите перевод на счет",
                        null=True,
                        verbose_name="Перевод",
                    ),
                ),
                (
                    "paid_course",
                    models.ManyToManyField(
                        blank=True,
                        help_text="укажите курс",
                        null=True,
                        to="course.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "paid_lesson",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Укажите урок",
                        null=True,
                        to="lesson.lesson",
                        verbose_name="Урок",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Укажите пользователя",
                        null=True,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
    ]
