# Generated by Django 5.0.6 on 2024-07-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
        ("lesson", "0002_alter_lesson_options"),
        (
            "payment",
            "0002_alter_payment_paid_course_alter_payment_paid_lesson_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="paid_course",
            field=models.ManyToManyField(
                blank=True,
                help_text="укажите курс",
                null=True,
                to="course.course",
                verbose_name="Курс",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="paid_lesson",
            field=models.ManyToManyField(
                blank=True,
                help_text="Укажите урок",
                null=True,
                to="lesson.lesson",
                verbose_name="Урок",
            ),
        ),
    ]
