# Generated by Django 5.0.6 on 2024-07-09 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lesson", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"verbose_name": "Урок", "verbose_name_plural": "Уроки"},
        ),
    ]
